### ISSUE TITLE
Is box_noise_dim not being used?

### ISSUE THREAD

**Issue by ennauata** [ashual/scene_generation#12]
Hi,

I could not find the usage of the box_noise_dim attribute in the Model class, is it being used in the code at all?
https://github.com/ashual/scene_generation/blob/e4b98ea437329b1a51deb67811e2b6593baa8ff6/scene_generation/model.py#L25

Also, can we expect the model to output different layouts when sampling the same input graph multiple times by running sample_images.py multiple times?
 
I would appreciate your feedback on this.
Best regards.

**Comment by ashual** [comment]
Hi,
As stated in the paper, we've ended up using a normal noise vector just for the masks.
Hence, the `box_noise_dim` attribute is no longer used in the final version. It can be removed.

The final layout is affected by two different things:
* The input graph - which we choose randomly using the objects GT attributes (i.e.when you run `sample_images.py` sometimes the graph can be `sky` -> `above` -> `grass` and sometimes `grass` -> `below` -> `sky` in a specific image)
* The layout noise - even if the input is the same graph, the layout can be different since we're adding random noise to the layout.

These two things give us diverse layouts, as we wanted.

**Comment by ennauata** [comment]
Now it's very clear to me. Thank you very much for addressing my questions!
