### ISSUE TITLE
Where is the autoencoder mentioned in the paper.

### ISSUE THREAD

**Issue by 3288103265** [ashual/scene_generation#15]
Hi, ashual. 
     An autoencoder for generation is adopted in your paper, but I can't find it in this repo. Actually, many GANs is seems to be responsible for generation, but GANs are generally different with autoencoder. So how can I understand it?

**Comment by ashual** [comment]
hi Wang Penghui,
the term auto-encoder is used only once in the paper when referring to the network _R_.
This is a **mistake**, the right term is encoder-decoder and not auto-encoder since the input and output are different.
When referring to _R_ in other places in the paper, the right term encoder-decoder is used.
Thanks for telling me
